// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-tile.cuh"

// TurboQuant instances: the tile kernel decodes the V cache itself instead of
// having launch_fattn expand it to f16 first. Only head sizes 128 and 256 exist
// because TurboQuant requires head_dim to be a multiple of 128.

DECL_FATTN_TILE_CASE_TURBO(128, 128, GGML_TYPE_TURBO3_0);
DECL_FATTN_TILE_CASE_TURBO(128, 128, GGML_TYPE_TURBO4_0);
DECL_FATTN_TILE_CASE_TURBO(256, 256, GGML_TYPE_TURBO3_0);
DECL_FATTN_TILE_CASE_TURBO(256, 256, GGML_TYPE_TURBO4_0);
